services:
  postgres_gaspo:
    image: postgres:16-alpine
    container_name: gaspo-postgres-gaspo
    environment:
      POSTGRES_DB: gaspo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gaspo123
    ports:
      - "15444:5432"
    volumes:
      - postgres_gaspo_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gaspo_db"]
      interval: 5s
      timeout: 5s
      retries: 20

  gaspo-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gaspo-api
    depends_on:
      postgres_gaspo:
        condition: service_healthy
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_gaspo:5432/gaspo_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: gaspo123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      WAIT_FOR_DB_HOSTS: postgres_gaspo:5432
    ports:
      - "18082:8081"
    restart: unless-stopped

volumes:
  postgres_gaspo_data:
