spring.application.name=gaspo
server.port=8081


#BANCO DE DADOS 1: E-SUS
#-----------------------------------------------------------------------------------------------------

# Configuracao do Banco de Dados e-SUS (A porta 5433)
spring.datasource.url=jdbc:postgresql://localhost:5432/esus_backup
spring.datasource.username=postgres
spring.datasource.password=12345678

# Diz para o Hibernate nao tentar criar/apagar as tabelas do governo (MUITO IMPORTANTE)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

#-----------------------------------------------------------------------------------------------------



#BANCO DE DADOS 2: GASPO
#-----------------------------------------------------------------------------------------------------

app.datasource.gaspo.url=jdbc:postgresql://localhost:5432/gaspo_db
app.datasource.gaspo.username=postgres
app.datasource.gaspo.password=gaspo123
app.datasource.gaspo.driver-class-name=org.postgresql.Driver

app.jpa.gaspo.hibernate.ddl-auto=update