spring.application.name=gaspo
server.port=8081

# Banco unico do GASPO
spring.datasource.url=jdbc:postgresql://localhost:15444/gaspo_db
spring.datasource.username=postgres
spring.datasource.password=gaspo123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

