spring.application.name=gaspo

# Configuração do Banco de Dados e-SUS (A porta 5433)
spring.datasource.url=jdbc:postgresql://localhost:5433/esus
spring.datasource.username=postgres
spring.datasource.password=A_SENHA_GIGANTE_QUE_VOCE_TEM

# Diz para o Hibernate não tentar criar/apagar as tabelas do governo (MUITO IMPORTANTE)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true